version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - "8087:80"
    volumes:
      - ./:/gousto
      - ./site.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:fpm
    volumes:
      - ./:/gousto

